# Generated by Django 2.2.7 on 2019-11-14 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('idAdresu', models.AutoField(primary_key=True, serialize=False)),
                ('miasto', models.CharField(max_length=35)),
                ('kodPocztowy', models.CharField(max_length=6)),
                ('nrDomu', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(3)])),
                ('nrLok', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idKlienta', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=25)),
                ('nazwisko', models.CharField(max_length=35)),
                ('telefon', models.IntegerField(validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
                ('adresEmail', models.CharField(max_length=35)),
                ('adres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('idPracownika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=25)),
                ('nazwisko', models.CharField(max_length=35)),
                ('telefon', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(9)])),
                ('dataZatrudnienia', models.DateField()),
                ('dataZwolnienia', models.DateField()),
                ('adres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('idZgloszenia', models.AutoField(primary_key=True, serialize=False)),
                ('dataPrzyjecia', models.DateField()),
                ('dataOdbioru', models.DateField()),
                ('typ', models.CharField(max_length=35)),
                ('cenaOstateczna', models.CharField(max_length=35)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Klient')),
            ],
        ),
        migrations.CreateModel(
            name='Realizacja',
            fields=[
                ('idRealizacji', models.AutoField(primary_key=True, serialize=False)),
                ('stan', models.CharField(max_length=35)),
                ('urzadzenie', models.CharField(max_length=35)),
                ('opisUsterki', models.CharField(max_length=100)),
                ('aktualnaWycena', models.CharField(max_length=35)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Pracownik')),
                ('zgloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Zgloszenie')),
            ],
        ),
    ]
