# Generated by Django 2.2.7 on 2019-11-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=35)),
                ('ulica', models.CharField(max_length=35)),
                ('nrDomu', models.IntegerField()),
                ('nrLok', models.IntegerField()),
                ('kodPocztowy', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=35)),
                ('adres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=35)),
                ('nazwisko', models.CharField(max_length=35)),
                ('telefon', models.CharField(max_length=15)),
                ('adresEmail', models.CharField(max_length=35)),
                ('adres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=35)),
                ('nazwisko', models.CharField(max_length=35)),
                ('specjalizacja', models.CharField(max_length=35)),
                ('login', models.CharField(max_length=35)),
                ('haslo', models.CharField(max_length=35)),
                ('telefon', models.CharField(max_length=15)),
                ('adresEmail', models.CharField(max_length=35)),
                ('czyZalogowany', models.BooleanField()),
                ('adres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataUtworzenia', models.DateField()),
                ('dataDostarczeniaUrzadzenia', models.DateField()),
                ('dataOdbioruUrzadzenia', models.DateField()),
                ('typZgloszenia', models.CharField(choices=[('NAP', 'Naprawa'), ('REK', 'Reklamacja'), ('INS_AKT_OPR', 'Instalacja/aktualizacja oprogramowania'), ('ODZ_DAN', 'Odzyskiwanie danych'), ('DZI_ANT', 'Działanie antywirusowe')], default='NAP', max_length=50)),
                ('stanRealizacji', models.CharField(choices=[('NOW', 'Nowe'), ('W_TRA', 'W trakcie realizacji'), ('GOT_DO_ODB', 'Gotowe do odbioru')], default='NOW', max_length=50)),
                ('urzadzenie', models.CharField(max_length=120)),
                ('trescZgloszenia', models.CharField(max_length=120)),
                ('odpowiedzPracownika', models.CharField(max_length=120)),
                ('cena', models.CharField(max_length=35)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Firma')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Klient')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwis_komputerowy.Pracownik')),
            ],
        ),
    ]
