# Generated by Django 2.2.7 on 2019-12-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis_komputerowy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='nrLok',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='cena',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='dataDostarczeniaUrzadzenia',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='dataOdbioruUrzadzenia',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='odpowiedzPracownika',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='stanRealizacji',
            field=models.CharField(choices=[('NOWE', 'Nowe'), ('W TRAKCIE REALIZACJI', 'W trakcie realizacji'), ('GOTOWE DO ODBIORU', 'Gotowe do odbioru')], default='NOWE', max_length=50),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='trescZgloszenia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='typZgloszenia',
            field=models.CharField(choices=[('NAPRAWA', 'Naprawa'), ('REKLAMACJA', 'Reklamacja'), ('INSTALACJA/AKTUALIZACJA OPROGRAMOWANIA', 'Instalacja/aktualizacja oprogramowania'), ('ODZYSKIWANIE DANYCH', 'Odzyskiwanie danych'), ('DZIALANIE ANTYWIRUSOWE', 'Działanie antywirusowe')], default='NAPRAWA', max_length=50),
        ),
    ]
