# Generated by Django 2.2.7 on 2020-01-18 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serwis_komputerowy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='odpowiedzPracownika',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pracownicy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='stanRealizacji',
            field=models.CharField(choices=[('NOWE', 'Nowe'), ('W TRAKCIE REALIZACJI', 'W trakcie realizacji'), ('GOTOWE DO ODBIORU', 'Gotowe do odbioru'), ('ZAKONCZONE', 'Zakończone')], default='NOWE', max_length=50),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='trescZgloszenia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='tworcaZgloszenia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Klienci', to=settings.AUTH_USER_MODEL),
        ),
    ]
