# Generated by Django 2.2.7 on 2020-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis_komputerowy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daneuzytkownika',
            name='specjalizacja',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
