# Generated by Django 2.2.7 on 2019-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis_komputerowy', '0002_auto_20191203_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='nrLok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='cena',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='dataDostarczeniaUrzadzenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='dataOdbioruUrzadzenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='odpowiedzPracownika',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='trescZgloszenia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
