# Generated by Django 2.2.7 on 2019-12-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serwis_komputerowy', '0003_auto_20191203_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name_plural': 'adresy'},
        ),
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name_plural': 'firmy'},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name_plural': 'klienci'},
        ),
        migrations.AlterModelOptions(
            name='pracownik',
            options={'verbose_name_plural': 'pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='zgloszenie',
            options={'verbose_name_plural': 'zgloszenia'},
        ),
    ]
